// Procedural texture bank. Every visual is generated by code (no external assets): shapes are baked
// once into GPU textures and then composed, animated and filtered by PixiJS (WebGL) every frame.

import { CanvasSource, Rectangle, Texture } from "pixi.js";
import { BALANCE } from "../config/balance";
import { hashString, Rng } from "../core/rng";
import type { RoomId } from "../meta/rooms";
import type { FacultyId } from "../social/faculties";
import { mix, PALETTE, rgba, shade } from "./color";
import { drawOrnamentBand, drawRoom } from "./rooms";
import { drawCrown } from "./shanyrak";

export const BLOCK_H = BALANCE.world.blockH;

export function makeCanvas(w: number, h: number): [HTMLCanvasElement, CanvasRenderingContext2D] {
  const c = document.createElement("canvas");
  c.width = Math.max(1, Math.ceil(w));
  c.height = Math.max(1, Math.ceil(h));
  const ctx = c.getContext("2d");
  if (!ctx) throw new Error("2D context unavailable");
  return [c, ctx];
}

/** Texture whose logical size is canvas size / resolution. */
export function canvasTexture(c: HTMLCanvasElement, resolution = 1): Texture {
  return new Texture({ source: new CanvasSource({ resource: c, resolution, antialias: true }) });
}

export interface Anchored {
  tex: Texture;
  /** Anchor (0..1) that puts the logical origin where the drawing code had (0,0). */
  ax: number;
  ay: number;
}

const ROOM_PAD_X = 14;
const ROOM_PAD_TOP = 22;
const ROOM_PAD_BOTTOM = 4;

export class TextureBank {
  private cache = new Map<string, unknown>();
  /** Pixels per world unit when baking (tracks screen scale × DPR, clamped). */
  scale = 2;

  private memo<T>(key: string, make: () => T): T {
    const hit = this.cache.get(key);
    if (hit !== undefined) return hit as T;
    const v = make();
    this.cache.set(key, v);
    return v;
  }

  // ── Rooms ──────────────────────────────────────────────────────────────

  room(type: RoomId, w: number, facade: string, ornament: string, faculty: FacultyId | null): Anchored {
    const qw = Math.round(w / 4) * 4;
    const k = this.scale;
    return this.memo(`room|${type}|${qw}|${facade}|${ornament}|${faculty}|${k}`, () => {
      const cw = qw + ROOM_PAD_X * 2;
      const ch = BLOCK_H + ROOM_PAD_TOP + ROOM_PAD_BOTTOM;
      const [c, ctx] = makeCanvas(cw * k, ch * k);
      ctx.scale(k, k);
      ctx.translate(cw / 2, BLOCK_H + ROOM_PAD_TOP);
      drawRoom(ctx, type, qw, BLOCK_H, {
        facade,
        ornament,
        faculty,
        studentSkin: "stu_classic",
        t: 0,
        glow: 0,
        students: 0,
        crack: 0,
        seed: 1,
        festive: false,
        baked: true,
      });
      return { tex: canvasTexture(c, k), ax: 0.5, ay: (BLOCK_H + ROOM_PAD_TOP) / ch };
    });
  }

  crack(w: number): Texture {
    const qw = Math.round(w / 8) * 8;
    return this.memo(`crack|${qw}|${this.scale}`, () => {
      const k = this.scale;
      const [c, ctx] = makeCanvas(qw * k, BLOCK_H * k);
      ctx.scale(k, k);
      ctx.strokeStyle = "rgba(27,15,8,0.6)";
      ctx.lineWidth = 1.7;
      const rng = new Rng(qw);
      for (let n = 0; n < 2; n++) {
        let x = qw * (0.2 + rng.next() * 0.6);
        let y = BLOCK_H * 0.22;
        ctx.beginPath();
        ctx.moveTo(x, y);
        for (let i = 0; i < 4; i++) {
          x += (rng.next() - 0.5) * 14;
          y += 6 + rng.next() * 6;
          ctx.lineTo(x, y);
        }
        ctx.stroke();
      }
      return canvasTexture(c, k);
    });
  }

  /** Warm arch-shaped light for a window (white-ish; tinted warm or cyan at runtime). */
  windowLight(ww: number, wh: number): Anchored {
    const qw = Math.round(ww);
    const qh = Math.round(wh);
    return this.memo(`win|${qw}|${qh}|${this.scale}`, () => {
      const k = this.scale;
      const halo = 10;
      const cw = qw + halo * 2;
      const chh = qh + halo * 2;
      const [c, ctx] = makeCanvas(cw * k, chh * k);
      ctx.scale(k, k);
      // halo
      const hg = ctx.createRadialGradient(cw / 2, chh / 2, 2, cw / 2, chh / 2, Math.max(cw, chh) * 0.6);
      hg.addColorStop(0, "rgba(255,240,200,0.35)");
      hg.addColorStop(1, "rgba(255,240,200,0)");
      ctx.fillStyle = hg;
      ctx.fillRect(0, 0, cw, chh);
      // arch pane
      const x = halo;
      const y = halo;
      ctx.beginPath();
      ctx.moveTo(x, y + qh);
      ctx.lineTo(x, y + qw / 2);
      ctx.arc(x + qw / 2, y + qw / 2, qw / 2, Math.PI, 0);
      ctx.lineTo(x + qw, y + qh);
      ctx.closePath();
      const g = ctx.createLinearGradient(0, y, 0, y + qh);
      g.addColorStop(0, "rgba(255,250,232,0.95)");
      g.addColorStop(1, "rgba(255,226,170,0.8)");
      ctx.fillStyle = g;
      ctx.fill();
      return { tex: canvasTexture(c, k), ax: halo / cw, ay: halo / chh };
    });
  }

  /** Small seamless wall ornament tile (cream, used at low alpha over the walls). */
  wallOrnament(kind: string): Texture {
    return this.memo(`wallorn|${kind}`, () => {
      const k = 2;
      const [c, ctx] = makeCanvas(36 * k, 30 * k);
      ctx.scale(k, k);
      drawOrnamentBand(ctx, kind, 0, 36, 15, 22, "#fff3d6");
      return canvasTexture(c, k);
    });
  }

  // ── Crown ──────────────────────────────────────────────────────────────

  crown(baseW: number, deco: string, ornament: string): Anchored {
    const qw = Math.round(baseW / 8) * 8;
    return this.memo(`crown|${qw}|${deco}|${ornament}|${this.scale}`, () => {
      const k = this.scale;
      const W = qw + 26;
      const H = W * 0.34;
      const cw = W + 80;
      const ch = H + 90;
      const [c, ctx] = makeCanvas(cw * k, ch * k);
      ctx.scale(k, k);
      ctx.translate(cw / 2, ch - 30);
      drawCrown(ctx, qw, { t: 0, deco, glow: 0, ornament });
      return { tex: canvasTexture(c, k), ax: 0.5, ay: (ch - 30) / ch };
    });
  }

  rays(): Texture {
    return this.memo("rays", () => {
      const size = 512;
      const [c, ctx] = makeCanvas(size, size);
      ctx.translate(size / 2, size / 2);
      for (let i = 0; i < 14; i++) {
        ctx.rotate((Math.PI * 2) / 14);
        const g = ctx.createLinearGradient(0, 0, size / 2, 0);
        g.addColorStop(0, "rgba(255,241,194,0.55)");
        g.addColorStop(1, "rgba(255,241,194,0)");
        ctx.fillStyle = g;
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.lineTo(size / 2, -size * 0.045);
        ctx.lineTo(size / 2, size * 0.045);
        ctx.closePath();
        ctx.fill();
      }
      return canvasTexture(c, 1);
    });
  }

  /** Soft radial dot (white), used for glows, halos and lights. */
  softDot(): Texture {
    return this.memo("softdot", () => {
      const size = 128;
      const [c, ctx] = makeCanvas(size, size);
      const g = ctx.createRadialGradient(size / 2, size / 2, 0, size / 2, size / 2, size / 2);
      g.addColorStop(0, "rgba(255,255,255,1)");
      g.addColorStop(0.35, "rgba(255,255,255,0.55)");
      g.addColorStop(1, "rgba(255,255,255,0)");
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, size, size);
      return canvasTexture(c, 1);
    });
  }

  /** Full-screen vignette (black edges). */
  vignette(): Texture {
    return this.memo("vignette", () => {
      const size = 256;
      const [c, ctx] = makeCanvas(size, size);
      const g = ctx.createRadialGradient(size / 2, size / 2, size * 0.25, size / 2, size / 2, size * 0.72);
      g.addColorStop(0, "rgba(0,0,0,0)");
      g.addColorStop(1, "rgba(0,0,0,1)");
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, size, size);
      return canvasTexture(c, 1);
    });
  }

  /** Spotlight cone (white, fading), for gym floodlights and lanterns. */
  cone(): Texture {
    return this.memo("cone", () => {
      const w = 64;
      const h = 160;
      const [c, ctx] = makeCanvas(w, h);
      const g = ctx.createLinearGradient(0, 0, 0, h);
      g.addColorStop(0, "rgba(255,255,255,0.7)");
      g.addColorStop(1, "rgba(255,255,255,0)");
      ctx.fillStyle = g;
      ctx.beginPath();
      ctx.moveTo(w / 2 - 4, 0);
      ctx.lineTo(w / 2 + 4, 0);
      ctx.lineTo(w, h);
      ctx.lineTo(0, h);
      ctx.closePath();
      ctx.fill();
      return canvasTexture(c, 1);
    });
  }

  // ── Particles: one atlas so every ParticleContainer shares a texture source ──

  particles(): Record<string, Texture> {
    return this.memo("particles", () => {
      const cell = 64;
      const kinds = ["spark", "glow", "dust", "chip", "confetti", "petal", "star", "coin", "snow", "rain", "wind", "steam", "fire", "leaf", "ring"];
      const cols = 5;
      const rows = Math.ceil(kinds.length / cols);
      const [c, ctx] = makeCanvas(cols * cell, rows * cell);
      const radial = (x: number, y: number, r: number, inner: number) => {
        const g = ctx.createRadialGradient(x, y, 0, x, y, r);
        g.addColorStop(0, "rgba(255,255,255,1)");
        g.addColorStop(inner, "rgba(255,255,255,0.7)");
        g.addColorStop(1, "rgba(255,255,255,0)");
        ctx.fillStyle = g;
        ctx.beginPath();
        ctx.arc(x, y, r, 0, Math.PI * 2);
        ctx.fill();
      };
      kinds.forEach((kind, i) => {
        const x0 = (i % cols) * cell;
        const y0 = Math.floor(i / cols) * cell;
        const cx = x0 + cell / 2;
        const cy = y0 + cell / 2;
        ctx.save();
        ctx.fillStyle = "#fff";
        ctx.strokeStyle = "#fff";
        switch (kind) {
          case "spark":
            radial(cx, cy, 14, 0.3);
            break;
          case "glow":
          case "steam":
          case "fire":
            radial(cx, cy, 30, kind === "fire" ? 0.25 : 0.1);
            break;
          case "dust":
            radial(cx, cy, 26, 0.5);
            break;
          case "chip":
            ctx.fillRect(cx - 10, cy - 6, 20, 12);
            break;
          case "confetti":
            ctx.fillRect(cx - 12, cy - 5, 24, 10);
            break;
          case "petal":
            ctx.beginPath();
            ctx.ellipse(cx, cy, 14, 7, 0, 0, Math.PI * 2);
            ctx.fill();
            break;
          case "leaf":
            ctx.beginPath();
            ctx.moveTo(cx - 14, cy + 6);
            ctx.quadraticCurveTo(cx - 12, cy - 12, cx + 14, cy - 8);
            ctx.quadraticCurveTo(cx + 10, cy + 10, cx - 14, cy + 6);
            ctx.fill();
            break;
          case "star":
            ctx.beginPath();
            for (let k = 0; k < 8; k++) {
              const r = k % 2 ? 6 : 22;
              const a = (k / 8) * Math.PI * 2;
              ctx.lineTo(cx + Math.cos(a) * r, cy + Math.sin(a) * r);
            }
            ctx.closePath();
            ctx.fill();
            radial(cx, cy, 10, 0.4);
            break;
          case "coin":
            ctx.fillStyle = PALETTE.gold;
            ctx.beginPath();
            ctx.arc(cx, cy, 16, 0, Math.PI * 2);
            ctx.fill();
            ctx.strokeStyle = PALETTE.goldDeep;
            ctx.lineWidth = 3;
            ctx.stroke();
            ctx.fillStyle = "#fff3c4";
            ctx.fillRect(cx - 3, cy - 8, 6, 16);
            break;
          case "snow":
            radial(cx, cy, 10, 0.6);
            break;
          case "rain":
            ctx.lineWidth = 3;
            ctx.lineCap = "round";
            ctx.beginPath();
            ctx.moveTo(cx, cy - 26);
            ctx.lineTo(cx, cy + 26);
            ctx.stroke();
            break;
          case "wind":
            ctx.lineWidth = 3;
            ctx.lineCap = "round";
            ctx.beginPath();
            ctx.moveTo(cx - 28, cy);
            ctx.quadraticCurveTo(cx, cy - 8, cx + 28, cy);
            ctx.stroke();
            break;
          case "ring":
            ctx.lineWidth = 4;
            ctx.beginPath();
            ctx.arc(cx, cy, 24, 0, Math.PI * 2);
            ctx.stroke();
            break;
        }
        ctx.restore();
      });
      const base = canvasTexture(c, 1);
      const out: Record<string, Texture> = {};
      kinds.forEach((kind, i) => {
        out[kind] = new Texture({ source: base.source, frame: new Rectangle((i % cols) * cell, Math.floor(i / cols) * cell, cell, cell) });
      });
      return out;
    });
  }

  // ── Landscape (seamless tiles for TilingSprite parallax) ─────────────────

  /** Seamless ridge: sum of sines with integer periods over the tile width. */
  private ridge(seed: string, width: number, amps: number[]): (x: number) => number {
    const rng = new Rng(hashString(seed));
    const terms = amps.map((a, i) => ({ a, p: (i + 1) * (1 + Math.floor(rng.next() * 2)), ph: rng.next() * Math.PI * 2 }));
    return (x: number) => terms.reduce((s, t) => s + t.a * Math.sin((x / width) * Math.PI * 2 * t.p + t.ph), 0);
  }

  mountainsTile(): Texture {
    return this.memo("mtn", () => {
      const w = 1024;
      const h = 320;
      const [c, ctx] = makeCanvas(w, h);
      const f = this.ridge("alatau", w, [60, 32, 18, 9]);
      const yAt = (x: number) => h * 0.42 - f(x);
      const body = ctx.createLinearGradient(0, 40, 0, h);
      body.addColorStop(0, "#e9eef8");
      body.addColorStop(1, "#9aa6c2");
      ctx.fillStyle = body;
      ctx.beginPath();
      ctx.moveTo(0, h);
      for (let x = 0; x <= w; x += 4) ctx.lineTo(x, yAt(x));
      ctx.lineTo(w, h);
      ctx.closePath();
      ctx.fill();
      // snow caps where the ridge is high
      ctx.save();
      ctx.clip();
      ctx.fillStyle = "#ffffff";
      ctx.beginPath();
      ctx.moveTo(0, h * 0.42 - 30);
      for (let x = 0; x <= w; x += 4) ctx.lineTo(x, Math.min(yAt(x) + 26 + 8 * Math.sin(x * 0.07), h * 0.42 - 24 + 10 * Math.sin(x * 0.05)));
      ctx.lineTo(w, 0);
      ctx.lineTo(0, 0);
      ctx.closePath();
      ctx.fill();
      // shaded slopes
      ctx.fillStyle = "rgba(60,70,110,0.18)";
      for (let x = 0; x < w; x += 24) {
        const y = yAt(x);
        ctx.beginPath();
        ctx.moveTo(x, y);
        ctx.lineTo(x + 30, h);
        ctx.lineTo(x + 12, h);
        ctx.closePath();
        ctx.fill();
      }
      ctx.restore();
      ctx.clearRect(0, 0, w, 2);
      ctx.clearRect(0, h - 2, w, 2);
      return canvasTexture(c, 1);
    });
  }

  hillsTile(): Texture {
    return this.memo("hills", () => {
      const w = 1024;
      const h = 200;
      const [c, ctx] = makeCanvas(w, h);
      const f = this.ridge("hills", w, [22, 12, 6]);
      ctx.fillStyle = "#ffffff";
      ctx.beginPath();
      ctx.moveTo(0, h);
      for (let x = 0; x <= w; x += 4) ctx.lineTo(x, h * 0.45 - f(x));
      ctx.lineTo(w, h);
      ctx.closePath();
      ctx.fill();
      // tree specks
      const rng = new Rng(9);
      ctx.fillStyle = "rgba(0,0,0,0.12)";
      for (let i = 0; i < 90; i++) {
        const x = rng.next() * w;
        const y = h * 0.45 - f(x) + 6 + rng.next() * 30;
        ctx.beginPath();
        ctx.arc(x, y, 3 + rng.next() * 4, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.clearRect(0, 0, w, 2);
      ctx.clearRect(0, h - 2, w, 2);
      return canvasTexture(c, 1);
    });
  }

  /** Third layer — depends on the equipped background cosmetic. */
  detailTile(kind: string): Texture {
    return this.memo(`detail|${kind}`, () => {
      const w = 1024;
      const h = 220;
      const [c, ctx] = makeCanvas(w, h);
      const rng = new Rng(hashString(kind));
      const base = h * 0.62;
      if (kind === "bg_city") {
        let x = 0;
        while (x < w) {
          const bw = 26 + rng.next() * 44;
          const bh = 40 + rng.next() * 110;
          const right = Math.min(w, x + bw - 3);
          ctx.fillStyle = "#ffffff";
          ctx.fillRect(x, base - bh, right - x, bh + h);
          x += bw;
        }
      } else if (kind === "bg_steppe") {
        const f = this.ridge("steppe", w, [6, 3]);
        ctx.fillStyle = "#ffffff";
        ctx.beginPath();
        ctx.moveTo(0, h);
        for (let x = 0; x <= w; x += 4) ctx.lineTo(x, base - f(x));
        ctx.lineTo(w, h);
        ctx.fill();
        for (let i = 0; i < 7; i++) {
          const yx = 60 + i * 140 + rng.next() * 40;
          const s = 12 + rng.next() * 6;
          const y = base - f(yx) + 2;
          ctx.fillStyle = "#f7f1e2";
          ctx.beginPath();
          ctx.moveTo(yx - s, y);
          ctx.lineTo(yx - s, y - s * 0.6);
          ctx.quadraticCurveTo(yx, y - s * 1.4, yx + s, y - s * 0.6);
          ctx.lineTo(yx + s, y);
          ctx.closePath();
          ctx.fill();
          ctx.fillStyle = "rgba(160,110,60,0.5)";
          ctx.fillRect(yx - s * 0.18, y - s * 0.5, s * 0.36, s * 0.5);
        }
      } else if (kind === "bg_lake") {
        ctx.fillStyle = "#ffffff";
        for (let x = 6; x < w; x += 22 + rng.next() * 18) {
          const s = 24 + rng.next() * 26;
          ctx.beginPath();
          ctx.moveTo(x, base - s);
          ctx.lineTo(x - s * 0.32, base);
          ctx.lineTo(x + s * 0.32, base);
          ctx.closePath();
          ctx.fill();
        }
        ctx.fillRect(0, base, w, h - base);
      } else {
        // Alatau foothills: rounded hills with small houses
        const f = this.ridge("foothills", w, [16, 8, 4]);
        ctx.fillStyle = "#ffffff";
        ctx.beginPath();
        ctx.moveTo(0, h);
        for (let x = 0; x <= w; x += 4) ctx.lineTo(x, base - 10 - f(x));
        ctx.lineTo(w, h);
        ctx.fill();
        ctx.fillStyle = "rgba(0,0,0,0.14)";
        for (let i = 0; i < 40; i++) {
          const x = rng.next() * w;
          const y = base - 6 - f(x) + rng.next() * 24;
          ctx.fillRect(x, y - 5, 8, 5);
        }
      }
      ctx.clearRect(0, 0, w, 2);
      ctx.clearRect(0, h - 2, w, 2);
      return canvasTexture(c, 1);
    });
  }

  /** Lights on the detail layer (shown at dusk/night). */
  lightsTile(kind: string): Texture {
    return this.memo(`lights|${kind}`, () => {
      const w = 1024;
      const h = 220;
      const [c, ctx] = makeCanvas(w, h);
      const rng = new Rng(hashString(`lights${kind}`));
      const base = h * 0.62;
      const n = kind === "bg_city" ? 420 : 90;
      for (let i = 0; i < n; i++) {
        const x = rng.next() * w;
        const y = kind === "bg_city" ? base - rng.next() * 140 : base - 4 + rng.next() * 30;
        ctx.fillStyle = rng.chance(0.75) ? "rgba(255,210,122,0.95)" : "rgba(255,243,196,0.95)";
        ctx.fillRect(x, y, 2, kind === "bg_city" ? 3 : 2);
      }
      ctx.clearRect(0, 0, w, 2);
      ctx.clearRect(0, h - 2, w, 2);
      return canvasTexture(c, 1);
    });
  }

  /** Foreground: grass tufts and stones (seamless). */
  foregroundTile(): Texture {
    return this.memo("fg", () => {
      const w = 1024;
      const h = 90;
      const [c, ctx] = makeCanvas(w, h);
      const rng = new Rng(31);
      for (let i = 0; i < 180; i++) {
        const x = rng.next() * w;
        const bh = 12 + rng.next() * 26;
        ctx.strokeStyle = rng.chance(0.5) ? "#3f7d48" : "#5c9e5f";
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(x, h);
        ctx.quadraticCurveTo(x + (rng.next() - 0.5) * 10, h - bh * 0.6, x + (rng.next() - 0.5) * 14, h - bh);
        ctx.stroke();
      }
      for (let i = 0; i < 16; i++) {
        const x = rng.next() * w;
        const r = 6 + rng.next() * 10;
        ctx.fillStyle = rng.chance(0.5) ? "#8b8478" : "#a39b8c";
        ctx.beginPath();
        ctx.ellipse(x, h - r * 0.4, r, r * 0.6, 0, Math.PI, 0);
        ctx.fill();
      }
      for (let i = 0; i < 26; i++) {
        const x = rng.next() * w;
        ctx.fillStyle = ["#ffd1dc", "#fff3c4", "#ff9ab8", "#ffffff"][i % 4];
        ctx.beginPath();
        ctx.arc(x, h - 10 - rng.next() * 18, 2.2, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.clearRect(0, 0, w, 2);
      return canvasTexture(c, 1);
    });
  }

  cloud(variant: number): Texture {
    return this.memo(`cloud|${variant}`, () => {
      const w = 320;
      const h = 120;
      const [c, ctx] = makeCanvas(w, h);
      const rng = new Rng(100 + variant);
      for (let i = 0; i < 9; i++) {
        const x = 50 + rng.next() * (w - 100);
        const y = 55 + (rng.next() - 0.5) * 30;
        const r = 26 + rng.next() * 30;
        const g = ctx.createRadialGradient(x, y, 0, x, y, r);
        g.addColorStop(0, "rgba(255,255,255,0.85)");
        g.addColorStop(1, "rgba(255,255,255,0)");
        ctx.fillStyle = g;
        ctx.beginPath();
        ctx.arc(x, y, r, 0, Math.PI * 2);
        ctx.fill();
      }
      return canvasTexture(c, 1);
    });
  }

  /** Low ground fog (white band, soft). */
  fog(): Texture {
    return this.memo("fog", () => {
      const w = 512;
      const h = 96;
      const [c, ctx] = makeCanvas(w, h);
      const g = ctx.createLinearGradient(0, 0, 0, h);
      g.addColorStop(0, "rgba(255,255,255,0)");
      g.addColorStop(0.55, "rgba(255,255,255,0.55)");
      g.addColorStop(1, "rgba(255,255,255,0)");
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, w, h);
      return canvasTexture(c, 1);
    });
  }

  tree(variant: number): Anchored {
    return this.memo(`tree|${variant}|${this.scale}`, () => {
      const k = this.scale;
      const w = 64;
      const h = 76;
      const [c, ctx] = makeCanvas(w * k, h * k);
      ctx.scale(k, k);
      ctx.fillStyle = "#6b4a2b";
      ctx.fillRect(w / 2 - 3, h - 30, 6, 30);
      const greens = variant % 2 ? ["#3f8f5a", "#57a96d"] : ["#4f9d69", "#6bbd80"];
      ctx.fillStyle = greens[0];
      ctx.beginPath();
      ctx.arc(w / 2, h - 44, 22, 0, Math.PI * 2);
      ctx.arc(w / 2 - 13, h - 33, 14, 0, Math.PI * 2);
      ctx.arc(w / 2 + 13, h - 34, 15, 0, Math.PI * 2);
      ctx.fill();
      ctx.fillStyle = greens[1];
      ctx.beginPath();
      ctx.arc(w / 2 - 6, h - 50, 10, 0, Math.PI * 2);
      ctx.fill();
      return { tex: canvasTexture(c, k), ax: 0.5, ay: 1 };
    });
  }

  lamp(): Anchored {
    return this.memo(`lamp|${this.scale}`, () => {
      const k = this.scale;
      const [c, ctx] = makeCanvas(16 * k, 56 * k);
      ctx.scale(k, k);
      ctx.fillStyle = "#2b2d40";
      ctx.fillRect(6.5, 8, 3, 48);
      ctx.fillStyle = "#3a3d55";
      ctx.fillRect(3, 5, 10, 4);
      ctx.fillStyle = "#ffe2a0";
      ctx.beginPath();
      ctx.arc(8, 8, 4.5, 0, Math.PI * 2);
      ctx.fill();
      return { tex: canvasTexture(c, k), ax: 0.5, ay: 1 };
    });
  }

  /** Flag cloth with a stripe pattern (TilingSprite scrolls it to fake waving). */
  flagCloth(color: string): Texture {
    return this.memo(`flag|${color}`, () => {
      const [c, ctx] = makeCanvas(64, 32);
      ctx.fillStyle = color;
      ctx.fillRect(0, 0, 64, 32);
      for (let x = 0; x < 64; x++) {
        const a = 0.18 * Math.sin((x / 64) * Math.PI * 4);
        ctx.fillStyle = a > 0 ? `rgba(255,255,255,${a})` : `rgba(0,0,0,${-a})`;
        ctx.fillRect(x, 0, 1, 32);
      }
      ctx.fillStyle = PALETTE.gold;
      ctx.beginPath();
      ctx.arc(32, 16, 6, 0, Math.PI * 2);
      ctx.fill();
      return canvasTexture(c, 1);
    });
  }

  /** Vertical sky gradient texture (repainted when the theme changes). */
  skyTexture(): { tex: Texture; paint(top: string, bottom: string): void } {
    return this.memo("sky", () => {
      const [c, ctx] = makeCanvas(4, 256);
      const tex = canvasTexture(c, 1);
      let last = "";
      return {
        tex,
        paint(top: string, bottom: string) {
          const key = top + bottom;
          if (key === last) return;
          last = key;
          const g = ctx.createLinearGradient(0, 0, 0, 256);
          g.addColorStop(0, top);
          g.addColorStop(1, bottom);
          ctx.fillStyle = g;
          ctx.fillRect(0, 0, 4, 256);
          tex.source.update();
        },
      };
    });
  }

  /** Plaza strip in front of the campus (world units: 1 unit = 1 px at scale 1). */
  plaza(width: number): Anchored {
    const qw = Math.round(width / 10) * 10;
    return this.memo(`plaza|${qw}|${this.scale}`, () => {
      const k = Math.min(this.scale, 2);
      const h = 22;
      const [c, ctx] = makeCanvas(qw * k, h * k);
      ctx.scale(k, k);
      ctx.fillStyle = "#cdb994";
      ctx.fillRect(0, 0, qw, h);
      ctx.fillStyle = "#b39d76";
      for (let x = 0; x < qw; x += 22) ctx.fillRect(x, 7, 1.5, h - 7);
      ctx.fillStyle = rgba("#000000", 0.12);
      ctx.fillRect(0, 0, qw, 3);
      ctx.fillStyle = mix("#cdb994", PALETTE.gold, 0.3);
      ctx.fillRect(qw / 2 - 30, 0, 60, h);
      ctx.fillStyle = shade("#cdb994", -0.15);
      for (let i = 0; i < 6; i++) ctx.fillRect(qw / 2 - 28 + i * 10, 3, 6, 2);
      return { tex: canvasTexture(c, k), ax: 0.5, ay: 0 };
    });
  }
}
